DROP TABLE IF EXISTS likes;
CREATE TABLE likes
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  ressource_id INTEGER REFERENCES ressources(id) ON DELETE CASCADE,
  liked BOOLEAN,
  created_at TIMESTAMP DEFAULT now()
);
